# Generated by Django 3.0.3 on 2020-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addphoto', '0002_auto_20200306_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_count', models.ManyToManyField(blank=True, related_name='fire_count', to='addphoto.UploadedPhoto')),
                ('haha_count', models.ManyToManyField(blank=True, related_name='haha_count', to='addphoto.UploadedPhoto')),
                ('poop_count', models.ManyToManyField(blank=True, related_name='poop_count', to='addphoto.UploadedPhoto')),
            ],
        ),
    ]
