# Generated by Django 3.0.3 on 2020-02-29 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registerpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extraUserDate',
            new_name='extraUserData',
        ),
    ]
