# Generated by Django 3.0.3 on 2020-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerpage', '0002_remove_extrauserdata_last_voted_pic_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extraUserData',
        ),
    ]
