# Generated by Django 3.0.3 on 2020-03-13 07:57

import addphoto.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPost', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(blank=True, max_length=140, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to=addphoto.models.get_image_path)),
                ('hahaStat', models.BigIntegerField(default=0)),
                ('fireStat', models.BigIntegerField(default=0)),
                ('poopStat', models.BigIntegerField(default=0)),
                ('fire_count', models.ManyToManyField(blank=True, related_name='fire_count', to=settings.AUTH_USER_MODEL)),
                ('haha_count', models.ManyToManyField(blank=True, related_name='haha_count', to=settings.AUTH_USER_MODEL)),
                ('poop_count', models.ManyToManyField(blank=True, related_name='poop_count', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addphoto.Seasons')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
