# Generated by Django 3.0.3 on 2020-03-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='fire_count',
        ),
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='haha_count',
        ),
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='poop_count',
        ),
    ]
