# Generated by Django 3.0.3 on 2020-03-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasons',
            name='name',
        ),
        migrations.AddField(
            model_name='seasons',
            name='season_number',
            field=models.IntegerField(default=0),
        ),
    ]
