# Generated by Django 3.0.3 on 2020-03-06 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addphoto', '0002_auto_20200306_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='haha_count',
            field=models.ManyToManyField(blank=True, related_name='haha_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
