# Generated by Django 3.0.3 on 2020-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0002_auto_20200315_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='caption',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
