# Generated by Django 3.0.3 on 2020-03-17 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addphoto', '0004_auto_20200315_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='noexStat',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='noex_count',
            field=models.ManyToManyField(blank=True, related_name='noex_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
