# Generated by Django 3.0.3 on 2020-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0005_uploadedphoto_poop_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='fireStat',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='hahaStat',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='poopStat',
            field=models.BigIntegerField(default=0),
        ),
    ]
