# Generated by Django 3.0.3 on 2020-03-01 10:44

import addphoto.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0005_auto_20200301_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to=addphoto.models.get_image_path),
        ),
    ]
