# Generated by Django 3.0.3 on 2020-03-01 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0006_auto_20200301_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='dateOfPost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
