# Generated by Django 3.0.3 on 2020-03-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addphoto', '0007_uploadedphoto_dateofpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='fire_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='haha_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedphoto',
            name='poop_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
