# Generated by Django 3.0.3 on 2020-03-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haha', models.BigIntegerField(default=0)),
                ('fire', models.BigIntegerField(default=0)),
                ('poop', models.BigIntegerField(default=0)),
            ],
        ),
    ]
