# Generated by Django 3.0.3 on 2020-03-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollModel',
        ),
    ]
